// 状态： { 0: '未开始', 1: '开发中',  2: '已完成' }
export const COM_STATUS = { 0: '未开始', 1: '开发中', 2: '已完成', 3: '暂不修改' };

export default [
  // name: Basic,
  { status: '3', owner: '', name: 'Icon 图标' },
  { status: '1', owner: 'kevin', name: 'Button 按钮' },
  { status: '3', owner: '', name: 'Link 文字链接' },

  // name: Form,
  { status: '2', owner: 'kevin', name: 'Radio 单选框' },
  { status: '2', owner: 'kevin', name: 'Checkbox 多选框' },
  { status: '2', owner: 'kevin', name: 'Input 输入框' },
  { status: '2', owner: 'kevin', name: 'InputNumber 计数器' },
  { status: '1', owner: 'kevin', name: 'Select 选择器' },
  { status: '3', owner: '', name: 'Cascader 级联选择器' },
  { status: '2', owner: '', name: 'Switch 开关' },
  { status: '0', owner: '', name: 'Slider 滑块' },
  { status: '0', owner: '', name: 'TimePicker 时间选择器' },
  { status: '0', owner: '', name: 'DatePicker 日期选择器' },
  { status: '0', owner: '', name: 'DateTimePicker 日期时间选择器' },
  { status: '0', owner: '', name: 'Upload 上传' },
  { status: '0', owner: '', name: 'Rate 评分' },
  { status: '0', owner: '', name: 'ColorPicker 颜色选择器' },
  { status: '0', owner: '', name: 'Transfer 穿梭框' },
  { status: '0', owner: 'kevin', name: 'Form 表单' },

  // name: Data
  { status: '1', owner: 'kevin', name: 'Table 表格' },
  { status: '0', owner: '', name: 'Tag 标签' },
  { status: '0', owner: '', name: 'Progress 进度条' },
  { status: '0', owner: '', name: 'Tree 树形控件' },
  { status: '2', owner: 'kevin', name: 'Pagination 分页' },
  { status: '0', owner: '', name: 'Badge 标记' },
  { status: '0', owner: '', name: 'Avatar 头像' },

  // name: Notice,
  { status: '2', owner: 'kevin', name: 'Alert 警告' },
  { status: '3', owner: 'kevin', name: 'Loading 加载' },
  { status: '2', owner: 'kevin', name: 'Message 消息提示' },
  { status: '2', owner: 'kevin', name: 'MessageBox 弹框' },
  { status: '2', owner: 'kevin', name: 'Notification 通知' },

  // name: Navigation,
  { status: '0', owner: 'kevin', name: 'NavMenu 导航菜单' },
  { status: '0', owner: '', name: 'Tabs 标签页' },
  { status: '0', owner: '', name: 'Breadcrumb 面包屑' },
  { status: '0', owner: '', name: 'PageHeader 页头' },
  { status: '0', owner: '', name: 'Dropdown 下拉菜单' },
  { status: '0', owner: '', name: 'Steps 步骤条' },

  // name: Others,
  { status: '0', owner: '', name: 'Dialog 对话框' },
  { status: '0', owner: '', name: 'Tooltip 文字提示' },
  { status: '1', owner: '547', name: 'Popover 弹出框' },
  { status: '1', owner: '547', name: 'Popconfirm 气泡确认框' },
  { status: '0', owner: '', name: 'Card 卡片' },
  { status: '0', owner: '', name: 'Carousel 走马灯' },
  { status: '1', owner: 'kevin', name: 'Collapse 折叠面板' },
  { status: '0', owner: '', name: 'Timeline 时间线' },
  { status: '3', owner: '', name: 'Divider 分割线' },
  { status: '0', owner: '', name: 'Calendar 日历' },
  { status: '3', owner: '', name: 'Image 图片' },
  { status: '3', owner: '', name: 'Backtop 回到顶部' },
  { status: '3', owner: '', name: 'InfiniteScroll 无限滚动' },
  { status: '2', owner: '547', name: 'Drawer 抽屉' },
];
